name: "build"
on:
    push:
    release:
        types: [published]
    workflow_dispatch:
jobs:
    build:
        name: "LaTeX Build" 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build LaTeX
              uses: xu-cheng/latex-action@v2
            - name: Install Make
              run: |
                apt install make
            - name: Build
              run: make
            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                name: linux
                path: |
                    2022-23/*.pdf
            # - name: Send Mail
            #   uses: dawidd6/action-send-mail@v3
            #   with:
            #     server_address: ${{secrets.EMAIL_HOST}}
            #     server_port: 587
            #     secure: true
            #     subject: The OS2G Journal has been updated!
            #     from: OS2G # <os2g@unl.edu>
            #     to: tgibbons2@huskers.unl.edu
            #     reply_to: os2g@unl.edu
            #     attachments: ./2022-23/journal.pdf
